#2) გაასწორეთ შემდეგი კოდი:
first_name = "Saba"
last_name = "Dzidzikashvili"
age = 17

print(first_name)
print(last_name)
print(age)

#3) გაასწორეთ შემდეგი კოდი:
name = "Saba"
surname = "Dzidzikashvili"
height = 182.3
favorite_number = 18 + 23

print(name)
print(surname)
print(height)
print(favorite_number)

#4) შექმენით 2 ცვლადი სადაც შეინახავთ განსხვავებულ რიცხვებს, შემდგომ გამოიყენეთ ამ ორ რიცხვზე ყველა მათემატიკური ოპერატორი და გამოიტანეთ ტერმინალში შედეგები.
num1 = 9
num2 = 15

print(num1 + num2)
print(num1 - num2)
print(num1 * num2)
print(num1 / num2)
print(num1 // num2)
print(num1 % num2)

#5) შექმენით 3 ცვლადი, სამივეში შეინახეთ განსხვავებული მონაცემთა ტიპის ინფორმაცია.


myname = ("Avtandili")
myage = 17
myweight = 53.5

print(myname)
print(myage)
print(myweight)